(use genturfahi test)

(include "empty-string.scm")
(include "end-of-input.scm")
(include "lerfu.scm")
(include "dot.scm")
(include "valsi.scm")
(include "optional.scm")
(include "zero-or-more.scm")
(include "one-or-more.scm")
(include "je.scm")
(include "jonai.scm")
(include "and-predicate.scm")
(include "not-predicate.scm")
(include "jonai-naselci.scm")
(include "samselpla.scm")
(include "re.scm")
(include "mex.scm")

(test-exit)
