;;;;
;;;; genturfahi - lo la .ckim. ke pe'a jajgau ratcu ke'e genturfa'i
;;;;            `-> A Scheme packrat parser.
;;;;
;;;; Copyright (c) 2010 ".alyn.post." <alyn.post@lodockikumazvati.org>
;;;;
;;;; Permission to use, copy, modify, and/or distribute this software for any
;;;; purpose with or without fee is hereby granted, provided that the above
;;;; copyright notice and this permission notice appear in all copies.
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
;;;; WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
;;;; MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
;;;; ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
;;;; WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
;;;; ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
;;;; OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
;;;;

string-escape <- (backslash-0
               / backslash-1
               / l-bracket-0
               / r-bracket-0
               / left-double-quote-1
               / right-double-quote-1
               / double-quote-1
               / left-single-quote-1
               / right-single-quote-1
               / single-quote-1
               / linefeed-0
               / linefeed-1
               / linefeed-2
               / newline-0
               / newline-1
               / newline-2
               / page-0
               / page-1
               / page-2
               / return-0
               / return-1
               / return-2
               / space-2
               / tab-0
               / tab-1
               / tab-2)*

backslash-0 <- [\\]
backslash-1 <- ,"\\"

l-bracket-0 <- [\[]
r-bracket-0 <- [\]]

left-double-quote-1 <- ,"\“"
right-double-quote-1 <- ,"\”"
double-quote-1 <- ,"\""

left-single-quote-1 <- ,"\‘"
right-single-quote-1 <- ,"\’"
single-quote-1 <- ,"\'"

linefeed-0 <- [\n]
linefeed-1 <- ,"\n"
linefeed-2 <- ,#\linefeed

newline-0 <- [\n]
newline-1 <- ,"\n"
newline-2 <- ,#\newline

page-0 <- [\f]
page-1 <- ,"\f"
page-2 <- ,#\page

return-0 <- [\r]
return-1 <- ,"\r"
return-2 <- ,#\return

space-2 <- ,#\space

tab-0 <- [\t]
tab-1 <- ,"\t"
tab-2 <- ,#\tab
